baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Tales from the Universe'
theme = 'paper'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
noClasses = false
